### ISSUE TITLE
Update Coroutines to 1.3.0

### ISSUE THREAD

**Issue by haroldadmin** [haroldadmin/Vector#2]
Coroutines 1.3.0-M1 is out.

The project should experiment with new changes right now and updated to the stable version when it is released.

**Comment by haroldadmin** [comment]
Update: Version 0.3.0 uses Coroutines 1.3.0-RC.
Will close this issue when 1.3.0 hits stable.

**Comment by Beer1234** [comment]
> Coroutines 1.3.0-M1 is out.
> 
> The project should experiment with new changes right now and updated to the stable version when it is released.

**Comment by haroldadmin** [comment]
Fixed with Version 0.4.2.
