### ISSUE TITLE
Update the README to have simple working example

### ISSUE THREAD

**Issue by kawpii** [haroldadmin/Vector#25]
**Is your feature request related to a problem? Please describe.**
Current example in the README is not complete and incorrect (cannot get it to work using the example code).

**Describe the solution you'd like**
Make the example on the README a working simple example. Something like [counter](https://github.com/airbnb/MvRx/tree/master/counter) example in MvRx

In addition please consider adding a module containing the working simple example to the repo.

**Comment by haroldadmin** [comment]
You're pointing out two separate issues here.

1. Lack of a simple sample app
2. Incomplete example in the project Readme.

For the first issue, i agree. We could use a simpler example app. Something like counter from MvRx would be perfect, but i don't want to have the exact same app. Perhaps something built using coroutines would be more apt. 

For the second issue, I disagree. The point of the Readme example is to quickly show how an app in Vector might look like. It doesn't aim to be a full fledged example. 

The only major things missing in the Readme example are complete Fragment setup, and implementation of the `MessageProvider` class. I think I'll just get rid of `MessageProvider` altogether, which should simplify things.

Either way, I'll try to implement these changes soon. Thanks for pointing them out :)

**Comment by haroldadmin** [comment]
Fixed with [simpler readme example](https://github.com/haroldadmin/Vector/commit/6d50006b1f8b567f9650399c6244fcf32fd543cc) and [simpler sample app](https://github.com/haroldadmin/Vector/commit/3f3eae8d34574cf65d903560dc7ed3a32675057f). Thanks for raising this issue!

**Comment by kaushalyap** [comment]
@haroldadmin I checked release apk sizes of your `hello-vector` and counter app in MvRx, apk size is almost equal. I expected that vector apk size to would be much smaller.
