### ISSUE TITLE
What to do about shared viewmodels with assisted injection?

### ISSUE THREAD

**Issue by vdtyson** [haroldadmin/Vector#30]
I have a shared viewmodel that I'd like to share in all of my vector fragments. I've tried injecting it like shown in the documentation but I get the error saying that the VectorViewModelFactory needs to be created to get an instance of the ViewModel. Help would be much appreciated.

**Comment by vdtyson** [comment]
I'm wondering what I should do to instantiate mainSharedViewModel here in particular:
https://github.com/vdtyson/StreetEats/blob/feature/firebase_authentication/AndroidStreetEats/app/src/main/java/com/versilistyson/androidstreeteats/presentation/ui/authentication/login/LoginFragment.kt

**Comment by haroldadmin** [comment]
Hi. I'm glad you're trying out Vector in your app.

The best way to share a ViewModel between multiple fragments is to scope it to their parent activity. 

Suppose in your app you have one activity and two fragments, and you want to share a ViewModel between these fragments. To accomplish this, create an instance of your ViewModel in your activity like this:

```kotlin
class MainActivity {
  val mainViewModel: MainViewModel by viewModel()
}
```

And request the `MainViewModel` in your fragments like this:

```kotlin
class FragmentOne {
  val mainViewModel: MainViewModel by activityViewModel()
}

class FragmentTwo {
  val mainViewModel: MainViewModel by activityViewModel()
}
```

When you do this, the mainViewModel parameter in `FragmentOne`, 'FragmentTwo`, and `MainActivity` will all refer to the same instance of the ViewModel as in your activity.

For a concrete example, you can checkout my app [MoonShot](https://www.github.com/haroldadmin/MoonShot) for an example:
[MainActivity.kt](https://github.com/haroldadmin/MoonShot/blob/b48a67770c4eea36a30dc020642bd1d207a50307/app/src/main/java/com/haroldadmin/moonshot/MainActivity.kt#L37)
[LaunchDetailsFragment.kt](https://github.com/haroldadmin/MoonShot/blob/b48a67770c4eea36a30dc020642bd1d207a50307/launchDetails/src/main/java/com/haroldadmin/moonshot/launchDetails/LaunchDetailsFragment.kt#L58)

**Comment by haroldadmin** [comment]
I forgot to add this in the reply, but the MoonShot example also shows you how to set this up with AssistedInject.
