### ISSUE TITLE
Compatibility with Android Studio 3.4

### ISSUE THREAD

**Issue by Quentin1010** [haroldadmin/Vector#5]
Could it be possible to be able to build this project on Android Studio 3.4?
Having to move to a beta version of AS to run it is a blocker for me...

**Comment by haroldadmin** [comment]
Android Studio 3.5 is already at RC 3, and will be released to stable very soon. They release weekly, and the last release was on Aug 8. So it should only take a couple of days.

**Comment by haroldadmin** [comment]
If you can not wait for a couple of days, I can maybe make separate branch with a lower AGP version so that you can build it on AS 3.5. Do you think that is a good idea?

**Comment by Quentin1010** [comment]
Yep I can wait for that to happen. I just found it weird as a practice to give an open project like that, np ^^

**Comment by haroldadmin** [comment]
AS 3.5 is stable, and I have updated the project to use AGP 3.5.0, and Kotlin 1.3.50. [Commit.](https://github.com/haroldadmin/Vector/commit/f9a4a654da3165ae751d2042342adb38f6fddd50)
